var contentJson = {

	//文章
	"article":[{
		"title":"UIKit性能调优实战讲解",
		"url":"http://www.jianshu.com/p/619cf14640f3"
	},
	{
		"title":"AutoLayout等分布局（Xib和Masonry）",
		"url":"http://www.henishuo.com/scrollview-autolayout/"
	},
	{
		"title":"AutoLayout",
		"url":"http://www.jianshu.com/p/052e8c7e8e7f"
	},
	{
		"title":"AutoLayout-VFL",
		"url":"http://mmmmmax.wang/2015/12/11/Auto-Layout-Visual-Format-Language-Tutorial/"
	},
	{
		"title":"AutoLayout，分析iOS各版本特性",
		"url":"http://www.starming.com/index.php?v=index&view=84"
	},
	{
		"title":"Autolayout与UIScrollview",
		"url":"http://www.jianshu.com/p/c67f9850158d?utm_campaign=hugo&utm_medium=reader_share&utm_content=note&utm_source=weibo"
	},
	{
		"title":"Nav:titleView动态缩放效果",
		"url":"http://www.jianshu.com/p/bcf3d692f99d?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io"
	},
	{
		"title":"WKWebView：API精讲",
		"url":"http://www.henishuo.com/wkwebview-objc/"
	},
	{
		"title":"WKWebView：Js实战",
		"url":"http://www.henishuo.com/wkwebview-js-h5-oc/"
	},
	{
		"title":"WKWebView：使用和各种坑的解决方法",
		"url":"http://www.jianshu.com/p/403853b63537?url_type=39&object_type=webpage&pos=1"
	},
	{
		"title":"WebView：本地缓存web图片/web图片点击方法",
		"url":"http://kittenyang.com/webview-javascript-bridge/"
	},
	{
		"title":"UITableView：性能优化",
		"url":"http://ios.jobbole.com/86851/"
	},
	{
		"title":"UIStackView",
		"url":"http://ios.jobbole.com/87146/"
	},
	{
		"title":"离屏渲染优化",
		"url":"http://mp.weixin.qq.com/s?__biz=MjM5NTIyNTUyMQ==&mid=2709544818&idx=1&sn=62d0d2e9a363d250beb2d6887dca54b3#rd"
	},
	{
		"title":"夜间模式解决方案",
		"url":"https://segmentfault.com/a/1190000005056914"
	},
	{
		"title":"iOS教你轻松打造瀑布流Layout",
		"url":"http://mp.weixin.qq.com/s?__biz=MzAxMzE2Mjc2Ng==&mid=2652154899&idx=1&sn=34f1d78640ca9d716932a9637d6e0528&scene=0#wechat_redirect"
	}
	],

	//gitHub
	"gitHub":[
	{
		"title":"获取FPS-OC方法",
		"url":"https://github.com/ibireme/YYText/blob/master/Demo/YYTextDemo/YYFPSLabel.m"
	},
	{
		"title":"获取FPS-Swift方法",
		"url":"https://github.com/Finb/V2ex-Swift/blob/master/View/V2FPSLabel.swift"
	},
	{
		"title":"低耗资源的圆角",
		"url":"https://github.com/raozhizhen/JMRoundedCorner"
	},
	{
		"title":"微信webview返回效果",
		"url":"https://github.com/Roxasora/RxWebViewController?url_type=39&object_type=webpage&pos=1"
	},
	{
		"title":"UIKitDynamics的几个demo",
		"url":"https://github.com/xiaofei86/UIKitDynamics"
	},
	{
		"title":"无限滚动Scroll",
		"url":"https://github.com/vvm/InfiniteScroll"
	},
	{
		"title":"滤镜 - demo：1.灰度图。有三种方法，a.求平均值b.取最大值c.做加权平均；2.黑白图，平均值大于0.5的可以当做黑色，小于0.5的可以当做白色。；3.底片图。rgb的每一个值取反（1-color.r, 1-color.g, 1-color.b, 1.0）；4.浮雕图。取当前的rgb,取第二个像素的rgb,算出差值,用差值+0.5,得到的结果,再进行下灰度计算",
		"url":"https://developer.apple.com/library/ios/samplecode/RosyWriter/Introduction/Intro.html"
	},
	{
		"title":"滤镜 - 磨皮：YUGPUImageHighPassSkinSmoothing",
		"url":"https://github.com/YuAo/YUGPUImageHighPassSkinSmoothing"
	},
	{
		"title":"IDMPhotoBrowser - 图片浏览",
		"url":"https://github.com/ideaismobile/IDMPhotoBrowser"
	}
	]
}
